// src/app/shared/header.component.ts
// src/app/shared/header.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <header class="bg-white shadow-sm border-b sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between items-center h-16">
          <div class="flex items-center">
            <h1 class="text-2xl font-bold text-blue-600">BookStore Pro</h1>
          </div>

          <nav class="hidden md:flex space-x-8">
            <a routerLink="/dashboard" routerLinkActive="text-blue-600" class="text-gray-700 hover:text-blue-600 transition-colors">Dashboard</a>
            <a routerLink="/books" routerLinkActive="text-blue-600" class="text-gray-700 hover:text-blue-600 transition-colors">Books</a>
            <a routerLink="/cart" routerLinkActive="text-blue-600" class="text-gray-700 hover:text-blue-600 transition-colors">Cart</a>
            <a routerLink="/profile" routerLinkActive="text-blue-600" class="text-gray-700 hover:text-blue-600 transition-colors">Profile</a>
            <a *ngIf="isAdmin" routerLink="/admin" routerLinkActive="text-blue-600" class="text-gray-700 hover:text-blue-600 transition-colors">Admin</a>
          </nav>

          <div class="flex items-center space-x-4">
            <button (click)="toggleCart()" class="relative p-2 text-gray-700 hover:text-blue-600">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4m0 0L7 13m0 0l-1.8 5.2a1 1 0 00.9 1.8h10.8m-2.4-6.8a1 1 0 100 2 1 1 0 000-2zm-7.2 0a1 1 0 100 2 1 1 0 000-2z"></path>
              </svg>
              <span *ngIf="cartCount > 0" class="absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center">
                {{cartCount}}
              </span>
            </button>

            <button (click)="toggleMobileMenu()" class="md:hidden p-2 text-gray-700">
              <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
              </svg>
            </button>

            <button (click)="logout()" class="text-gray-700 hover:text-red-600 transition-colors">
              Logout
            </button>
          </div>
        </div>

        <!-- Mobile menu -->
        <div *ngIf="mobileMenuOpen" class="md:hidden py-4 border-t">
          <nav class="space-y-2">
            <a routerLink="/dashboard" class="block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md">Dashboard</a>
            <a routerLink="/books" class="block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md">Books</a>
            <a routerLink="/cart" class="block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md">Cart</a>
            <a routerLink="/profile" class="block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md">Profile</a>
            <a *ngIf="isAdmin" routerLink="/admin" class="block px-3 py-2 text-gray-700 hover:bg-gray-50 rounded-md">Admin</a>
          </nav>
        </div>
      </div>
    </header>
  `
})
export class HeaderComponent {
  private router = inject(Router);
  
  mobileMenuOpen = false;
  cartCount = 0;
  isAdmin = false;

  constructor() {
    this.checkUserRole();
  }

  checkUserRole() {
    const user = JSON.parse(localStorage.getItem('user') || '{}');
    this.isAdmin = user.role === 'admin' || user.role === 'super_admin';
  }

  toggleMobileMenu() {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  toggleCart() {
    this.router.navigate(['/cart']);
  }

  logout() {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    this.router.navigate(['/auth']);
  }
}

// src/components/layout/Header.tsx
"use client"

import type React from "react"
import { useState } from "react"
import { Link, useNavigate } from "react-router-dom"
import { Search, ShoppingCart, User, LogOut, Settings } from "lucide-react"
import { useAuth } from "@/hooks/useAuth"
import { useCartStore } from "@/stores/cart"
import { Button } from "@/components/ui/Button"
import { Input } from "@/components/ui/Input"
import { Menu as HeadlessMenu } from "@headlessui/react"

export const Header: React.FC = () => {
  const { user, isAuthenticated, logout } = useAuth()
  const { itemCount } = useCartStore()
  const navigate = useNavigate()
  const [searchQuery, setSearchQuery] = useState("")

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    if (searchQuery.trim()) {
      navigate(`/books?search=${encodeURIComponent(searchQuery)}`)
    }
  }

  const handleLogout = async () => {
    await logout()
    navigate("/login")
  }

  return (
    <header className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <Link to="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <span className="text-white font-bold text-lg">B</span>
            </div>
            <span className="text-xl font-bold text-gray-900 dark:text-white">BookStore</span>
          </Link>

          {/* Search */}
          <div className="flex-1 max-w-lg mx-8">
            <form onSubmit={handleSearch} className="relative">
              <Input
                type="text"
                placeholder="Search books, authors, categories..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-gray-400" />
            </form>
          </div>

          {/* Navigation */}
          <div className="flex items-center space-x-4">
            {isAuthenticated ? (
              <>
                {/* Cart */}
                <Link
                  to="/cart"
                  className="relative p-2 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white"
                >
                  <ShoppingCart className="h-6 w-6" />
                  {itemCount > 0 && (
                    <span className="absolute -top-1 -right-1 bg-red-500 text-white text-xs rounded-full h-5 w-5 flex items-center justify-center">
                      {itemCount}
                    </span>
                  )}
                </Link>

                {/* User Menu */}
                <HeadlessMenu as="div" className="relative">
                  <HeadlessMenu.Button className="flex items-center space-x-2 p-2 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
                    <User className="h-6 w-6" />
                    <span className="hidden md:block">{user?.first_name}</span>
                  </HeadlessMenu.Button>

                  <HeadlessMenu.Items className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 rounded-md shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none z-50">
                    <div className="py-1">
                      <HeadlessMenu.Item>
                        {({ active }) => (
                          <Link
                            to="/profile"
                            className={`${active ? "bg-gray-100 dark:bg-gray-700" : ""} flex items-center px-4 py-2 text-sm text-gray-700 dark:text-gray-300`}
                          >
                            <User className="mr-3 h-4 w-4" />
                            Profile
                          </Link>
                        )}
                      </HeadlessMenu.Item>

                      <HeadlessMenu.Item>
                        {({ active }) => (
                          <Link
                            to="/orders"
                            className={`${active ? "bg-gray-100 dark:bg-gray-700" : ""} flex items-center px-4 py-2 text-sm text-gray-700 dark:text-gray-300`}
                          >
                            <Settings className="mr-3 h-4 w-4" />
                            Orders
                          </Link>
                        )}
                      </HeadlessMenu.Item>

                      {user?.role === "admin" && (
                        <HeadlessMenu.Item>
                          {({ active }) => (
                            <Link
                              to="/admin"
                              className={`${active ? "bg-gray-100 dark:bg-gray-700" : ""} flex items-center px-4 py-2 text-sm text-gray-700 dark:text-gray-300`}
                            >
                              <Settings className="mr-3 h-4 w-4" />
                              Admin
                            </Link>
                          )}
                        </HeadlessMenu.Item>
                      )}

                      <HeadlessMenu.Item>
                        {({ active }) => (
                          <button
                            onClick={handleLogout}
                            className={`${active ? "bg-gray-100 dark:bg-gray-700" : ""} flex items-center w-full px-4 py-2 text-sm text-gray-700 dark:text-gray-300`}
                          >
                            <LogOut className="mr-3 h-4 w-4" />
                            Logout
                          </button>
                        )}
                      </HeadlessMenu.Item>
                    </div>
                  </HeadlessMenu.Items>
                </HeadlessMenu>
              </>
            ) : (
              <div className="flex items-center space-x-2">
                <Button variant="ghost" onClick={() => navigate("/login")}>
                  Login
                </Button>
                <Button onClick={() => navigate("/register")}>Sign Up</Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </header>
  )
}
